name: Update IPTV Stable

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # 🔥 هذا هو الحل

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Download M3U8
        run: |
          rm -f playlist.m3u8

          curl -L \
            --retry 10 \
            --retry-delay 5 \
            --continue-at - \
            "http://1gotv.org:8080/get.php?username=4640441086618762&password=4640441086618762&type=m3u_plus&output=m3u8" \
            -o playlist.m3u8

      - name: Commit & Push
        run: |
          git config --global user.name "iptv-bot"
          git config --global user.email "iptv@bot.com"
          git add playlist.m3u8
          git commit -m "Update IPTV" || echo "No changes"
          git push
